### Contents

1 Import libraries and datasets  
2 Prepare population dataset  
3 Prepare densities dataset  
4 Merge datasets  
5 Export dataframe

### 1 Import libraries and datasets

In [3]:
import pandas as pd
import numpy as np
import os

In [5]:
# Create path
path = r"C:\Users\cathe\OneDrive\Data Analysis\2 6 Schools in England and Wales\02 Data\Prepared Data"

In [7]:
df1 = pd.read_csv(os.path.join(path, "schools_cleaned.csv"), index_col=False)

In [9]:
df2 = pd.read_csv(os.path.join(path, "population_cleaned.csv"), index_col=False)

In [11]:
df3 = pd.read_csv(os.path.join(path, "densities_cleaned.csv"), index_col=False)

### 2 Prepare population dataset

In [15]:
df2.columns

Index(['Unnamed: 0', 'Code', 'Name', 'Geography', 'All ages', '0', '1', '2',
       '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15',
       '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27',
       '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39',
       '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51',
       '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63',
       '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75',
       '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87',
       '88', '89', '90+'],
      dtype='object')

Rename "All ages" column as "Total Population of LA"  
Change type of population columns to integer  
Create columns:
- "Pre-school age" counting 0-3 year olds
- "Primary age" counting 4-10 year olds
- "Secondary age" counting 11-17 year olds
- "Total under 18s" counting 0-17 year olds

In [37]:
# Change column name
df2.rename(columns = {"All ages" : "Total Population of LA"}, inplace = True)

In [43]:
# Change column types to integer
df2['0'] = df2['0'].str.replace(',', '').astype(int)
df2['1'] = df2['1'].str.replace(',', '').astype(int)
df2['2'] = df2['2'].str.replace(',', '').astype(int)
df2['3'] = df2['3'].str.replace(',', '').astype(int)
df2['4'] = df2['4'].str.replace(',', '').astype(int)
df2['5'] = df2['5'].str.replace(',', '').astype(int)
df2['6'] = df2['6'].str.replace(',', '').astype(int)
df2['7'] = df2['7'].str.replace(',', '').astype(int)
df2['8'] = df2['8'].str.replace(',', '').astype(int)
df2['9'] = df2['9'].str.replace(',', '').astype(int)
df2['10'] = df2['10'].str.replace(',', '').astype(int)
df2['11'] = df2['11'].str.replace(',', '').astype(int)
df2['12'] = df2['12'].str.replace(',', '').astype(int)
df2['13'] = df2['13'].str.replace(',', '').astype(int)
df2['14'] = df2['14'].str.replace(',', '').astype(int)
df2['15'] = df2['15'].str.replace(',', '').astype(int)
df2['16'] = df2['16'].str.replace(',', '').astype(int)
df2['17'] = df2['17'].str.replace(',', '').astype(int)
df2['Total Population of LA'] = df2['Total Population of LA'].str.replace(',', '').astype(int)

In [45]:
# Create "Pre-school age" column
df2["Pre-school age"] = df2["0"] + df2["1"] + df2["2"] + df2["3"]

In [47]:
# Create "Primary age" column
df2["Primary age"] = df2["4"] + df2["5"] + df2["6"] + df2["7"] + df2["8"] + df2["9"] + df2["10"]

In [49]:
# Create "Secondary age" column
df2["Secondary age"] = df2["11"] + df2["12"] + df2["13"] + df2["14"] + df2["15"] + df2["16"] + df2["17"]

In [51]:
# Create "Total under 18s" column
df2["Total under 18s"] = df2["Pre-school age"] + df2["Primary age"] + df2["Secondary age"]

In [53]:
df2.columns

Index(['Unnamed: 0', 'Code', 'Name', 'Geography', 'Total Population of LA',
       '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60',
       '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72',
       '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84',
       '85', '86', '87', '88', '89', '90+', 'Pre-school age', 'Primary age',
       'Secondary age', 'Total under 18s'],
      dtype='object')

In [55]:
df2.head()

,Unnamed: 0,Code,Name,Geography,Total Population of LA,0,1,2,3,4,...,85,86,87,88,89,90+,Pre-school age,Primary age,Secondary age,Total under 18s
0,0,K04000001,ENGLAND AND WALES,Country,60854727,600801,641879,638385,661083,672685,...,"250,133","222,324","195,657","170,123","142,674","551,758",2542148,4927593,5148873,12618614
1,1,E92000001,ENGLAND,Country,57690323,573100,611983,608924,629972,640658,...,"235,873","209,664","184,536","160,616","134,632","521,291",2423979,4685594,4889073,11998646
2,2,E12000001,NORTH EAST,Region,2711380,24711,26256,26370,26959,28242,...,"11,874","10,641","8,949","8,003","6,504","23,914",104296,210064,220867,535227
3,3,E06000047,County Durham,Unitary Authority,532182,4410,4736,4805,4964,5084,...,"2,361","2,164","1,825","1,596","1,284","4,497",18915,38737,41977,99629
4,4,E06000005,Darlington,Unitary Authority,110562,1010,1115,1102,1157,1168,...,503,448,377,354,277,"1,083",4384,8655,9372,22411

In [81]:
# List of columns to keep
columns_to_keep = ["Local authority", "Total Population of LA", "Pre-school age", "Primary age", "Secondary age", "Total under 18s"]

In [83]:
df2_wrangled = df2[columns_to_keep]

In [79]:
# Change name of column Name to match df1
df2.rename(columns = {'Name' : 'Local authority'}, inplace = True)

C:\Users\cathe\AppData\Local\Temp\ipykernel_21964\3482384753.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_wrangled.rename(columns = {'Name' : 'Local authority'}, inplace = True)

In [85]:
df2_wrangled.head()

,Local authority,Total Population of LA,Pre-school age,Primary age,Secondary age,Total under 18s
0,ENGLAND AND WALES,60854727,2542148,4927593,5148873,12618614
1,ENGLAND,57690323,2423979,4685594,4889073,11998646
2,NORTH EAST,2711380,104296,210064,220867,535227
3,County Durham,532182,18915,38737,41977,99629
4,Darlington,110562,4384,8655,9372,22411

### 3 Prepare densities dataset

In [66]:
df3.head()

,Unnamed: 0,Lower Tier Local Authorities Code,Lower Tier Local Authorities,Population Density
0,0,E06000001,Hartlepool,985.5
1,1,E06000002,Middlesbrough,2671.2
2,2,E06000003,Redcar and Cleveland,557.1
3,3,E06000004,Stockton-on-Tees,959.3
4,4,E06000005,Darlington,545.9

In [ ]:
df3 = df3.drop(columns = ["Unnamed: 0"])

In [105]:
df3 = df3.drop(columns = ["Lower Tier Local Authorities Code"])

In [87]:
df3.rename(columns = {"Lower Tier Local Authorities" : "Local authority"}, inplace=True)

### 4 Merge datasets

In [89]:
df1.head(1)

,Unnamed: 0,URN,Ofsted phase,School open date,Admissions policy,Sixth form,Region,Local authority,Postcode,The income deprivation affecting children index (IDACI) quintile,...,Effectiveness of leadership and management,Previous graded inspection number,Previous inspection start date,Previous publication date,School type at time of previous graded inspection,Previous graded inspection overall effectiveness,Previous quality of education,Previous behaviour and attitudes,Previous personal development,Previous effectiveness of leadership and management
0,0,100000,Primary,NaN,Not applicable,Does not have a sixth form,London,City of London,EC3A 5DE,4.0,...,1.0,ITS411816,18/04/2013,14/05/2013,Voluntary Aided School,1.0,9.0,9.0,9.0,1.0

In [91]:
df1 = df1.drop(columns = ["Unnamed: 0"])

In [93]:
# Merge df1 and df2
df1and2 = df1.merge(df2_wrangled, on = 'Local authority', indicator=True)

In [95]:
df1and2.head(1)

,URN,Ofsted phase,School open date,Admissions policy,Sixth form,Region,Local authority,Postcode,The income deprivation affecting children index (IDACI) quintile,Total number of pupils,...,Previous quality of education,Previous behaviour and attitudes,Previous personal development,Previous effectiveness of leadership and management,Total Population of LA,Pre-school age,Primary age,Secondary age,Total under 18s,_merge
0,100000,Primary,NaN,Not applicable,Does not have a sixth form,London,City of London,EC3A 5DE,4.0,244.0,...,9.0,9.0,9.0,1.0,13462,183,235,224,642,both

In [97]:
df1and2["_merge"].value_counts()

_merge
both          21066
left_only         0
right_only        0
Name: count, dtype: int64

In [107]:
df3.head(1)

  Local authority  Population Density
0      Hartlepool               985.5

In [111]:
# Remove _merge flag column
df1and2 = df1and2.drop(columns = ["_merge"])

In [113]:
# Merge df1and2 with df3
df_merged = df1and2.merge(df3, on = 'Local authority', indicator=True)

In [115]:
df_merged.head(1)

,URN,Ofsted phase,School open date,Admissions policy,Sixth form,Region,Local authority,Postcode,The income deprivation affecting children index (IDACI) quintile,Total number of pupils,...,Previous behaviour and attitudes,Previous personal development,Previous effectiveness of leadership and management,Total Population of LA,Pre-school age,Primary age,Secondary age,Total under 18s,Population Density,_merge
0,100000,Primary,NaN,Not applicable,Does not have a sixth form,London,City of London,EC3A 5DE,4.0,244.0,...,9.0,9.0,1.0,13462,183,235,224,642,2975.0,both

In [117]:
df_merged["_merge"].value_counts()

_merge
both          12144
left_only         0
right_only        0
Name: count, dtype: int64

Merge successful!

In [120]:
# Remove _merge flag column
df_merged = df_merged.drop(columns = ["_merge"])

### 5 Export dataframe

In [ ]:
df_merged.to_csv(os.path.join(path, "complete_data_v1.csv"))